### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by krzysztofantczak** [google/module-server#4]
Hello there.

First of all, this project seems to be amazing idea, and it looks like that it is a 'tiny' missing bit in modules management process. I have started playing around with it, it's really really awesome. I've managed to make it works with few component.io components, now i'll try to run it with browserify modules and perhaps some of r.js dedicated ones, i can see right now that there is a little bit more work on this project, to make it really usable but my question is: Is this project abandoned already?

Best regards,
Chris

**Comment by godspeedelbow** [comment]
@krzysztofantczak I also think this is a very interesting project, I've reached out to @cramforce on Twitter to see what's up. I have done a quick google and I don't see any other projects that do the same thing.

I have forked the project to comment the code and figure out how it's working.

**Comment by cramforce** [comment]
Yeah, resolved on Twitter. Happy to fix bugs if anything comes up!!!
